### PR TITLE
added gitignore, fileio and gson helper class

### PR DESCRIPTION
**Pull request by jbcuglietta**

### CODE REVIEW

**Comment by Mobius5150** [comment]
@jbcuglietta  Looks better but there's still a bunch of binary files (for ex. in the .gradle) directory.

Try a bigger gitignore: https://www.gitignore.io/api/radle%2Cmaven%2Cosx%2Cwindows%2Candroid%2Clinux%2Ceclipse

Also if you add new commits to your master branch they'll automatically show up in the PR so no need to create a new one.

**Comment by jbcuglietta** [comment]
added bigger gitignore, gradle files might be neccessary for the android build.

**Comment by jbcuglietta** [comment]
also i dont know why there are conflicts in the merge

**Comment by Mobius5150** [comment]
I don't know about the conflicts, but I don't think that you need those files.

The original repo the sample is from doesn't have them: https://github.com/googlesamples/android-BluetoothLeGatt

**Comment by Mobius5150** [comment]
And if you leave binary files belonging to the build process in the source it's going to make for alot of trouble merging in the future

**Pull request closed without merging**
